---
title: "Assignment 3"
author: "ting"
date: "October 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
K1 <- read.csv("Class_Motivation.csv")
K2 <- dplyr::select(K1, 2:6)
K3 <- na.omit(K2)
K3 <- scale(K3)
fit <- kmeans(K3, 2)
fit$cluster
K4 <- data.frame(K3, fit$cluster)
names(K4) <- c("1", "2", "3", "4", "5", "cluster")
K5 <- tidyr::gather(K4, "week", "motivation", 1:5)
K6 <- K5 %>% group_by(week, cluster)
K6 <- summarise(K6, avg = mean(motivation))
K6$week <- as.numeric(K6$week)
K6$cluster <- as.factor(K6$cluster)
ggplot(K6, aes(week, avg, colour = cluster)) + geom_line() + xlab("Week") + ylab("Average Motivation")
#K7 <- dplyr::count(K4, cluster)
```

# 3 clusters
```{r}
K1 <- read.csv("Class_Motivation.csv")
K2 <- dplyr::select(K1, 2:6)
K3 <- na.omit(K2)
K3 <- scale(K3)
fit <- kmeans(K3, 3)
fit$cluster
K4 <- data.frame(K3, fit$cluster)
names(K4) <- c("1", "2", "3", "4", "5", "cluster")
K5 <- tidyr::gather(K4, "week", "motivation", 1:5)
K6 <- K5 %>% group_by(week, cluster)
K6 <- summarise(K6, avg = mean(motivation))
K6$week <- as.numeric(K6$week)
K6$cluster <- as.factor(K6$cluster)
ggplot(K6, aes(week, avg, colour = cluster)) + geom_line() + xlab("Week") + ylab("Average Motivation")
K7 <- dplyr::count(K4, cluster)

```